targets:
  $default:
    sources:
      - $package$
      - pubspec.yaml
      - lib/**
      - test/**
    builders:
      pubspec_generator:
        options:
          output: example/lib/src/common/constant/pubspec.yaml.g.dart